version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: weekly
      day: sunday
      
  - package-ecosystem: "nuget"
    directory: "/source/WebApp"
    schedule: 
      interval: weekly
      day: saturday